jobs:
  include:
    - os: windows
      language: c
      arch: arm64
      before_install:
        - cmake --version
        - git --version
        - git --help
        - systeminfo
        - wmic cpu get deviceid, name, numberofcores, numberoflogicalprocessors, maxclockspeed, status
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: windows
      language: c
      arch: ppc64le
      before_install:
        - cmake --version
        - git --version
        - git --help
        - systeminfo
        - wmic cpu get deviceid, name, numberofcores, numberoflogicalprocessors, maxclockspeed, status
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: windows
      language: c
      arch: s390x
      before_install:
        - cmake --version
        - git --version
        - git --help
        - systeminfo
        - wmic cpu get deviceid, name, numberofcores, numberoflogicalprocessors, maxclockspeed, status
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
#     - os: osx
#       language: c
#       arch: arm64
#       before_install:
#         - cmake --version
#         - git --version
#         - git --help
#         - hg --version
#         - svn --version
#         - clang --version
#         - uname -a
#         - lscpu
#         - free -h
#         - lshw -short
#       script:
#         - clang -coverage -O0 hello_world.c -o hello_world
#         - ./hello_world
#     - os: osx
#       language: c
#       arch: ppc64le
#       before_install:
#         - cmake --version
#         - git --version
#         - git --help
#         - hg --version
#         - svn --version
#         - clang --version
#         - uname -a
#         - lscpu
#         - free -h
#         - lshw -short
#       script:
#         - clang -coverage -O0 hello_world.c -o hello_world
#         - ./hello_world
#     - os: osx
#       language: c
#       arch: s390x
#       before_install:
#         - cmake --version
#         - git --version
#         - git --help
#         - hg --version
#         - svn --version
#         - clang --version
#         - uname -a
#         - lscpu
#         - free -h
#         - lshw -short
#       script:
#         - clang -coverage -O0 hello_world.c -o hello_world
#         - ./hello_world
    - os: freebsd
      language: c
      arch: arm64
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - dmesg
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: freebsd
      language: c
      arch: ppc64le
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - dmesg
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: freebsd
      language: c
      arch: s390x
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - dmesg
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: arm64
      dist: focal
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: ppc64le
      dist: focal
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: s390x
      dist: focal
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: arm64
      dist: xenial
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: ppc64le
      dist: xenial
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: s390x
      dist: xenial
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: arm64
      dist: bionic
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: ppc64le
      dist: bionic
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os: linux
      language: c
      arch: s390x
      dist: bionic
      before_install:
        - cmake --version
        - git --version
        - git --help
        - uname -a
        - lscpu
        - free -h
        - lshw -short
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
